// <auto-generated />
using CalculadoraPrestamo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraPrestamo.Migrations
{
    [DbContext(typeof(CalculadoraPrestamoWeb))]
    [Migration("20230605225730_SegundaMigracion")]
    partial class SegundaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraPrestamo.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CalculadoraPrestamo.Models.ConsultaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMeses")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CreditoId")
                        .HasColumnType("int");

                    b.Property<long>("MontoPrestamo")
                        .HasColumnType("bigint");

                    b.Property<float>("TasaInteres")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ConsultaPrestamo");
                });

            modelBuilder.Entity("CalculadoraPrestamo.Models.Credito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("CalculadoraPrestamo.Models.Interes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditoId")
                        .HasColumnType("int");

                    b.Property<int>("RangoInferior")
                        .HasColumnType("int");

                    b.Property<int>("RangoSuperior")
                        .HasColumnType("int");

                    b.Property<float>("TasaInteres")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CreditoId");

                    b.ToTable("Interes");
                });

            modelBuilder.Entity("CalculadoraPrestamo.Models.Interes", b =>
                {
                    b.HasOne("CalculadoraPrestamo.Models.Credito", "Credito")
                        .WithMany()
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");
                });
#pragma warning restore 612, 618
        }
    }
}
